media:
  input: public/covers
  output: /covers
  rename: true
  categories: [image]

content:
  - name: posts
    label: Articles
    type: collection
    path: src/content/posts
    format: yaml-frontmatter
    fields:
      - name: title
        label: Titre
        type: string
      - name: body
        label: Contenu
        type: rich-text

  - name: site
    label: Réglages du site
    type: file
    path: src/data/site.yml
    format: yaml
    fields:
      - name: siteName
        label: Nom du site
        type: string
      - name: baseline
        label: Baseline
        type: text
